# Generated by Django 3.2.4 on 2021-08-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_category_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='salutation',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Other', 'Other')], default='Mr', max_length=6),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
