# Generated by Django 3.2.4 on 2021-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210831_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainsliderimgs/')),
            ],
        ),
    ]
