# Generated by Django 3.2.4 on 2021-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='youremail@gmail.com', max_length=100, unique=True),
        ),
    ]
