# Generated by Django 3.2.4 on 2021-09-29 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('time', models.DateField(default=datetime.datetime(2021, 9, 29, 13, 32, 56, 683798))),
            ],
        ),
    ]
