# Generated by Django 3.2.4 on 2021-10-06 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20210930_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 16, 45, 0, 718761)),
        ),
    ]
